#pragma once

#define PRODUCT_ID   0x6509
#define DEVICE_VER   0x0001
#define PRODUCTION   Mechlovin9

#define MATRIX_ROW_PINS { A4, A5, A3, A2, A1 }
#define MATRIX_COL_PINS { B11, B10, B2, B1, B0, A7, A6, A0, C15, B4, B5, B3, C13, C14, A13 }

#define DIODE_DIRECTION COL2ROW

#define LED_CAPS_LOCK_PIN B9

#define BACKLIGHT_PIN B8
#define BACKLIGHT_BREATHING
#define BACKLIGHT_PWM_DRIVER PWMD3
#define BACKLIGHT_PWM_CHANNEL 3

#define BACKLIGHT_LEVELS 3
